//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.SocialSimRos
{
    public class MObstacleArray : Message
    {
        public const string RosMessageName = "social_sim_ros/ObstacleArray";

        //  Message defining an array of all obstacles in the environment
        public MHeader header;
        //  Timestamp and frame_id (should be "map")
        public MObstacle[] obstacles;
        //  Array containing all tracked obstacles

        public MObstacleArray()
        {
            this.header = new MHeader();
            this.obstacles = new MObstacle[0];
        }

        public MObstacleArray(MHeader header, MObstacle[] obstacles)
        {
            this.header = header;
            this.obstacles = obstacles;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(obstacles.Length));
            foreach(var entry in obstacles)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            
            var obstaclesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.obstacles= new MObstacle[obstaclesArrayLength];
            for(var i = 0; i < obstaclesArrayLength; i++)
            {
                this.obstacles[i] = new MObstacle();
                offset = this.obstacles[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MObstacleArray: " +
            "\nheader: " + header.ToString() +
            "\nobstacles: " + System.String.Join(", ", obstacles.ToList());
        }
    }
}
