//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SocialSimRos
{
    public class MObstacle : Message
    {
        public const string RosMessageName = "social_sim_ros/Obstacle";

        //  Message defining a single obstacle in the environment
        public int id;
        //  Unique identifier for this obstacle
        public string type;
        //  Obstacle category (box, cylinder, wall, furniture, etc.)
        public Geometry.MPose pose;
        //  Position and orientation in map frame
        public Geometry.MVector3 scale;
        //  Dimensions of the obstacle (x, y, z)

        public MObstacle()
        {
            this.id = 0;
            this.type = "";
            this.pose = new Geometry.MPose();
            this.scale = new Geometry.MVector3();
        }

        public MObstacle(int id, string type, Geometry.MPose pose, Geometry.MVector3 scale)
        {
            this.id = id;
            this.type = type;
            this.pose = pose;
            this.scale = scale;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.id));
            listOfSerializations.Add(SerializeString(this.type));
            listOfSerializations.AddRange(pose.SerializationStatements());
            listOfSerializations.AddRange(scale.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.id = BitConverter.ToInt32(data, offset);
            offset += 4;
            var typeStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.type = DeserializeString(data, offset, typeStringBytesLength);
            offset += typeStringBytesLength;
            offset = this.pose.Deserialize(data, offset);
            offset = this.scale.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MObstacle: " +
            "\nid: " + id.ToString() +
            "\ntype: " + type.ToString() +
            "\npose: " + pose.ToString() +
            "\nscale: " + scale.ToString();
        }
    }
}
